name: 'Unique PR Labels'
description: 'When a label is added on a PR, make sure it remains unique'
author: 'Stephdotnet'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  token:
    description: 'Github token with pull-requests: write permission'
    required: true

# Define your outputs here.
outputs:
  labels:
    description: 'Labels that were synced'

runs:
  using: node20
  main: dist/index.js
